# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Manual Selective Runs 

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Select which tests to run - default run all"
        required: false
        default: "All"
        type: choice
        options:
        - "All"
        - "5 and 6"
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if Google Chrome and ChromeDriver are installed
      id: check_installation
      run: |
        # Check Google Chrome
        if command -v google-chrome &> /dev/null; then
          echo "Google Chrome is installed."
          echo "CHROME_INSTALLED=true" >> $GITHUB_ENV
        else
          echo "Google Chrome is not installed."
          echo "CHROME_INSTALLED=false" >> $GITHUB_ENV
        fi

        # Check ChromeDriver
        if command -v chromedriver &> /dev/null; then
          echo "ChromeDriver is installed."
          echo "CHROMEDRIVER_INSTALLED=true" >> $GITHUB_ENV
        else
          echo "ChromeDriver is not installed."
          echo "CHROMEDRIVER_INSTALLED=false" >> $GITHUB_ENV
        fi

    - name: Install Chrome and Chromedriver
      if: env.CHROME_INSTALLED == 'false' || env.CHROMEDRIVER_INSTALLED == 'false'
      uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: true

    - name: Test with pytest
      run: |
        if [ "${{ github.event.inputs.tags }}" = "5 and 6" ]; then
          xvfb-run -a pytest tests/ -v -s -m custom56
        else
          xvfb-run -a pytest tests/ -v -s
        fi
